---
- hosts: 192.168.123.18
  gather_facts: yes
  become: yes
  tasks:
    - name: Create directory for share
      file:
        path: "/mnt/share"
        state: directory
        mode: "u=rwx,g=rx,o="
    - name: Create a new primary partition with a size of 100GiB
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 100GiB

    - name: Create a ext4 filesystem on /dev/sdb1
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: Mount VM Share
      ansible.posix.mount:
        path: /mnt/share
        src: /dev/sdb1
        fstype: ext4
        state: present
        passno: 2
    
    - name: Mount auto
      shell: sudo mount -a

    